export const SET_ITEMS = "ITEMS/SET_ITEMS";
export const SET_ITEM_DETAIL = "ITEM/SET_ITEM_DETAIL";
export const SET_LOADING_FETCH = "LOADING/SET_LOADING_FETCH";
export const SET_LOADING_ADD = "LOADING/SET_LOADING_ADD";
export const SET_LOADING_EDIT = "LOADING/SET_LOADING_EDIT";
