export const SET_IS_LOGGED_IN = "BOOL/SET_IS_LOGGED_IN";
export const SET_ACCESS_TOKEN = "TOKEN/SET_ACCESS_TOKEN";
export const SET_LOADING_LOGIN = "LOADING/SET_LOADING";
export const SET_LOADING_REGISTER = "LOADING/SET_LOADING";
